api:
  listen: ":1984"

rtsp:
  listen: ":8554"

webrtc:
  listen: ":8555/tcp"

streams:
  south_panel:
    - rtsp://${PANEL_USER}:${PANEL_PASSWORD}@${PANEL_HOST}:554/videolive
  south_cam1:
    - rtsp://${CAM_USER}:${CAM1_PASSWORD}@${CAM1_HOST}:554/Streaming/Channels/101
  south_cam2:
    - rtsp://${CAM_USER}:${CAM2_PASSWORD}@${CAM2_HOST}:554/Streaming/Channels/101
