api:
  listen: ":1984"

rtsp:
  listen: ":8554"

webrtc:
  listen: ":8555/tcp"

streams:
  south_panel:
    - rtsp://admin:${PANEL_PASSWORD}@192.168.1.20:554/videolive
  south_cam1:
    - rtsp://admin:${CAM1_PASSWORD}@192.168.70.160:554/Streaming/Channels/101
  south_cam2:
    - rtsp://admin:${CAM2_PASSWORD}@192.168.1.32:554/Streaming/Channels/101
