default_config:

homeassistant:
  name: Building Intercom
  unit_system: metric
  currency: BGN
  country: BG
  time_zone: Europe/Sofia

automation: !include automations.yaml

rest_command:
  open_south_door:
    url: !env_var OPEN_SOUTH_DOOR_URL
    method: GET
